config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
resources :home
resources :beneficiaries
resources :metric_dashboard_views

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/beneficiary.rb
class Beneficiary < ApplicationRecord
end

app/models/metric_dashboard_view.rb
class MetricDashboardView < ApplicationRecord
 has_many :metric_view_contents
 has_many :metric_details, through: :metric_view_contents

 accepts_nested_attributes_for :metric_view_contents
 

end

app/models/metric_detail.rb
class MetricDetail < ApplicationRecord
 has_many :metric_view_contents
 has_many :metric_dashboard_views, through: :metric_view_contents
end

app/models/metric_view_content.rb
class MetricViewContent < ApplicationRecord
	belongs_to :metric_detail
	belongs_to :metic_dashbord_view
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/beneficiaries_controller.rb
class BeneficiariesController < ApplicationController

def new
  @beneficiary = Beneficiary.new  
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
 # raise params.inspect	
end

end

app/controllers/metric_dashboard_views_controller.rb
class MetricDashboardViewsController < ApplicationController
  layout :false
  def index
   end

  def new
  	@metric_dashboard_view = MetricDashboardView.new
  	MetricDetail.all.each do |x|
  	 @metric_dashboard_view.metric_view_contents.build(metric_dashboard_view_id: x.id)
  	end
   flash[:notice] = 'Sucessfully created'

  	
  end

  def create
    # raise params.inspect
    @metric_dashboard_view = MetricDashboardView.new
    flash[:notice] = 'Sucessfully created'
    render 'new'
  end

  def dashboard_params
  	params.require(:metric_dashboard_view).permit(:id, :name, metric_view_contents: [
      :metric_order_number
    ])
  end
end

app/controllers/metric_details_controller.rb
class MetricDetailsController < ApplicationController
end

app/controllers/metric_view_contents_controller.rb
class MetricViewContentsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
def bootstrap_class_for(flash_type)
  case flash_type
  when "success"
    "alert-success"   # Green
  when "error"
    "alert-danger"    # Red
  when "alert"
    "alert-warning"   # Yellow
  when "notice"
    "alert-info"      # Blue
  else
    flash_type.to_s
    raise flash_type.inspect
  end
end
end

app/helpers/beneficiaries_helper.rb
module BeneficiariesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metric_dashboard_views_helper.rb
module MetricDashboardViewsHelper
end

app/helpers/metric_details_helper.rb
module MetricDetailsHelper
end

app/helpers/metric_view_contents_helper.rb
module MetricViewContentsHelper
end

app/views/beneficiaries/_form.html.erb
<!-- Row start -->
<div class="row gutters">
<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">


<!-- Card starts -->
<div class="card">
<div class="card-body">


<!-- Row start -->
<div class="row justify-content-center gutters">
	<div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
		<form>
			<div class="form-block">
				<div class="form-block-header">
					<h5>New Beneficiary</h5>
					<h6>Add you details here.</h6>
				</div>
				<div class="form-block-body">
					<div class="form-group">
						  <%= f.input :unique_id,placeholder: 'Member Id', label: false %>
					</div>
					<div class="form-group">
						  <%= f.input :name,placeholder: 'Name', label: false %>
					</div>
					<div class="form-group">
						  <%= f.input :email,placeholder: 'Email', label: false %>
					</div>
					<div class="form-group">
						  <%= f.input :name,placeholder: 'Mobile Number', label: false %>
					</div>

					<div class="form-group">
						<textarea class="form-control" id="message" placeholder="Message" maxlength="140" rows="5"></textarea>
						<div class="form-text text-muted">
							<p id="characterLeft" class="help-block">You have reached the limit</p>
						</div>
					</div>
					
					<button type="button" id="submit" name="submit" class="btn btn-primary pull-right">Submit Form</button>
				</div>
			</div>
		</form>
	</div>
</div>
<!-- Row end -->

app/views/beneficiaries/new.html.erb
<%= simple_form_for @beneficiary do |f| %>
<%= render 'form', f: f%>
<% end %>

app/views/home/index.html.erb
<!-- Row start -->
<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12">
	<div class="mini-widget">
		<div class="mini-widget-heading clearfix">
			<div class="float-left">Sales</div>
			<div class="float-right"><i class="icon-arrow-up-right2"></i> 12.2%</div>
		</div>
		<div class="mini-widget-body clearfix">
			<div class="float-left">
				<i class="icon-chart-pie"></i>
			</div>
			<div class="float-right number">8957</div>
		</div>
	</div>
</div>
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12">
	<div class="mini-widget red">
		<div class="mini-widget-heading clearfix">
			<div class="float-left">Tweets</div>
			<div class="float-right"><i class="icon-arrow-up-right2"></i> 18.3%</div>
		</div>
		<div class="mini-widget-body clearfix">
			<div class="float-left">
				<i class="icon-social-twitter"></i>
			</div>
			<div class="float-right number">3780</div>
		</div>
	</div>
</div>
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12">
	<div class="mini-widget grey">
		<div class="mini-widget-heading clearfix">
			<div class="float-left">Visitors</div>
			<div class="float-right"><i class="icon-arrow-down-right2"></i> 21.9%</div>
		</div>
		<div class="mini-widget-body clearfix">
			<div class="float-left">
				<i class="icon-eye2"></i>
			</div>
			<div class="float-right number">9670</div>
		</div>
	</div>
</div>
<div class="col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12">
	<div class="mini-widget grey">
		<div class="mini-widget-heading clearfix">
			<div class="float-left">Signups</div>
			<div class="float-right"><i class="icon-arrow-up-right2"></i> 67%</div>
		</div>
		<div class="mini-widget-body clearfix">
			<div class="float-left">
				<i class="icon-cloud-storage"></i>
			</div>
			<div class="float-right number">1590</div>
		</div>
	</div>
</div>
</div>
<!-- Row end -->

<!-- Row start -->
<div class="row gutters">						
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
	<div class="card">
		<div class="card-header">Chart One</div>
		<div class="toggle-switch tr">
			<input type="checkbox" class="check">
			<b class="b switch"></b>
			<b class="b track"></b>
		</div>
		<div class="card-body ">
			<div class="chartist custom-area-blue">
				<div class="lineArea">
					<%= pie_chart User.group(:name).count %>


				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
	<div class="card">
		<div class="card-header">Chart One</div>
		<div class="toggle-switch tr">
			<input type="checkbox" class="check">
			<b class="b switch"></b>
			<b class="b track"></b>
		</div>
		<div class="card-body ">
			<div class="chartist custom-area-blue">
				<div class="lineArea">
				<%= column_chart User.group_by_hour_of_day(:created_at, format: "%l %P").count %>

				</div>
			</div>
		</div>
	</div>
</div>
</div>
<!-- Row ends -->

<!-- Row start -->
<div class="row gutters">						
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
	<div class="card">
		<div class="card-header">Chart One</div>
		<div class="toggle-switch tr">
			<input type="checkbox" class="check">
			<b class="b switch"></b>
			<b class="b track"></b>
		</div>
		<div class="card-body ">
			<div class="chartist custom-area-blue">
				<div class="lineArea">
					<%= bar_chart User.group(:name).sum(:id) %>


				</div>
			</div>
		</div>
	</div>
</div>
<div class="col-xl-6 col-lg-6 col-md-12 col-sm-12 col-12">
	<div class="card">
		<div class="card-header">Chart One</div>
		<div class="toggle-switch tr">
			<input type="checkbox" class="check">
			<b class="b switch"></b>
			<b class="b track"></b>
		</div>
		<div class="card-body ">
			<div class="chartist custom-area-blue">
				<div class="lineArea">
					<%#= geo_chart User.group(:name).count %>

				</div>
			</div>
		</div>
	</div>
</div>
</div>
<!-- Row ends -->

app/views/layouts/_headers.html.erb
             <ul class="header-actions">
                <li class="dropdown">
                  <a href="#" id="notifications" data-toggle="dropdown" aria-haspopup="true">
                    <i class="icon-warning4"></i>
                    <span class="count-label">7</span>
                  </a>
                  <div class="dropdown-menu lg dropdown-menu-right" aria-labelledby="notifications">
                    <ul class="imp-notify">
                      <li>
                        <div class="icon">W</div>
                        <div class="details">
                          <h6 class="username">Deva</h6>
                          <p class="desc">The best Dashboard design I have seen ever.</p>
                          <p class="time">6:30 PM</p>
                        </div>
                      </li>
                      <li>
                    </ul>
                  </div>
                </li>
                <li>
                  <a href="#" id="todos" data-toggle="dropdown" aria-haspopup="true">
                    <i class="icon-archive3"></i>
                    <span class="count-label red">5</span>
                  </a>
                  <div class="dropdown-menu lg dropdown-menu-right" aria-labelledby="todos">
                    <ul class="tasks-widget">
                      <li>
                        <p>Task #48<span>90%</span></p>
                        <div class="progress">
                          <div class="progress-bar bg-success" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%">
                            <span class="sr-only">90% Complete (success)</span>
                          </div>
                        </div>
                      </li>
                      <li>
                        <p>Task #98<span>60%</span></p>
                        <div class="progress">
                          <div class="progress-bar bg-info" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
                            <span class="sr-only">60% Complete (success)</span>
                          </div>
                        </div>
                      </li>
                      <li>
                        <p>Task #7<span>40%</span></p>
                        <div class="progress">
                          <div class="progress-bar bg-danger" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                            <span class="sr-only">40% Complete (success)</span>
                          </div>
                        </div>
                      </li>
                    </ul>
                  </div>
                </li>
                <li class="dropdown">
                  <a href="#" id="userSettings" class="user-settings clearfix" data-toggle="dropdown" aria-haspopup="true">
                    <span class="avatar">
                      <i class="icon-account_circle"></i>
                    </span>
                    <span class="user-name">Deva <i class="icon-chevron-small-down downarrow"></i></span>
                  </a>
                  <div class="dropdown-menu md dropdown-menu-right" aria-labelledby="userSettings">
                    <div class="admin-settings">
                      <ul class="admin-settings-list">
                        <li>
                          <a href="profile.html">
                            <span class="icon icon-face"></span>
                            <span class="text-name">My Profile</span>
                            <span class="badge badge-success">75% Complete</span>
                          </a>
                        </li>
                        <li>
                          <a href="notifications.html">
                            <span class="icon icon-notifications_none"></span>
                            <span class="text-name">Notifications</span>
                            <span class="badge badge-orange">12</span>
                          </a>
                        </li>
                        <li>
                          <a href="secure.html">
                            <span class="icon icon-av_timer"></span>
                            <span class="text-name">Secure Account</span>
                          </a>
                        </li>
                      </ul>
                      <div class="actions">
                        <a href="login.html" class="btn btn-primary">Logout</a>
                      </div>
                    </div>
                  </div>
                </li>
              </ul>
 

app/views/layouts/_menus.html.erb
        <nav class="navbar navbar-expand-lg navbar-menu">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon">
              <i class="icon-menu5"></i>
            </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
              <li class="nav-item dropdown active">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-dashboards" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-blur_on"></i>
                  <span class="nav-item">Dashboards</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <%= link_to "Dashboard", home_index_path, class: "dropdown-item" %>
                  <a class="dropdown-item" href="home/index.html">Dashboard</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-apps" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-widgets"></i>
                  <span class="nav-item">Accounts</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="chat.html">Chat App</a>
                  <%= link_to "Beneficiaries", new_beneficiary_path, class: "dropdown-item" %>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-layouts" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-web"></i>
                  <span class="nav-item">Layouts</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="layout.html">Home</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-pages" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-business_center"></i>
                  <span class="nav-item">Pages</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="blog.html">Blog</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-forms" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-business_center"></i>
                  <span class="nav-item">Forms</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="bs-select.html">BS Select</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-ui-elements" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-style"></i>
                  <span class="nav-item">UI Elements</span>                 
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="general-elements.html">General Elements</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-tables" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-view_week"></i>
                  <span class="nav-item">Tables</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="tables.html">Tables</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-graphs" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-terrain"></i>
                  <span class="nav-item">Graphs</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="c3-graphs.html">C3 Graphs</a>
                </div>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="bluemoon-authentication" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <i class="nav-icon icon-lock-open"></i>
                  <span class="nav-item">Admin</span>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <a class="dropdown-item" href="login.html">Users</a>
                  <a class="dropdown-item" href="signup.html">Profiles</a>

                </div>
              </li>
            </ul>
          </div>
        </nav>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="Bluemoon Admin Panel" />
    <meta name="keywords" content="Admin" />
    <link rel="shortcut icon" href="favicon.ico" />
    <title>Test Title</title>
    

    <title>Fertile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>


    <!-- Loading start -->
    <div id="loading-wrapper">
      <div id="loader"></div>
    </div>
    <!-- Loading end -->



    <!-- BEGIN .app-wrap -->
    <div class="app-wrap">


      <!-- BEGIN .app-heading -->
      <header class="app-header">
        <div class="container-fluid">

          <!-- Row start -->
          <div class="row gutters">
            <div class="col-xl-4 col-lg-4 col-md-4 col-sm-4 col-4">
              
              <!-- BEGIN .logo -->
              <div class="logo-block">
                <a href="index.html" class="logo">
                  <%= image_tag("logo.png",  alt: "Bluemoon Admin Dashboard") %>

                </a>
              </div>
              <!-- END .logo -->

            </div>
            <div class="col-xl-8 col-lg-8 col-md-8 col-sm-8 col-8">

              <!-- Header actions start -->
              <%= render 'layouts/headers' %>

              <!-- Header actions end -->

              <!-- Custom Search start -->
              <div class="custom-search">
                <input type="text" class="search-query" placeholder="Search here ...">
                <i class="icon-search"></i>
              </div>
              <!-- Custom Search end -->

            </div>
          </div>
          <!-- Row start -->

        </div>
      </header>
      <!-- END: .app-heading -->




      <!-- BEGIN: .app-container -->
      <div class="app-container">




        <!-- BEGIN: Main navigation -->
         <%= render 'layouts/menus' %>

        <!-- END: Main navigation -->




        <!-- BEGIN: .page-header, Title of the Page -->
        <header class="page-header">
          <div class="container-fluid">
            <div class="row">
              <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="page-title">
                  <h3>Default Layout</h3>
                </div>
              </div>
            </div>
          </div>
        </header>
        <!-- END: .page-header -->




        <!-- BEGIN: .main-content -->
        <div class="main-content">
          <%= yield %>

          
        </div>
        <!-- END: .main-content -->




        <!-- BEGIN: .main-footer -->
        <footer class="main-footer">© Deva - 2018</footer>
        <!-- END: .main-footer -->





      </div>
      <!-- END: .app-container -->

    </div>
    <!-- END: .app-wrap -->
    
  </body>
</html>

app/views/metric_dashboard_views/new.html.erb
               <%= render partial: "shared/flash_messages", flash: flash %> 

<%= simple_form_for @metric_dashboard_view do |f| %>
  <%#= f.input :name, label: 'Your username please', error: 'Username is mandatory, please specify one' %>

 
 <%#=   f.collection_check_boxes :metric_view_contents_ids, f.object.metric_view_contents, :id, :name%> 
 <%#=   f.collection_check_boxes :metric_d_ids, MetricDetail.all, :id, :name%> 
 
  <%#= f.fields_for :metric_view_contents do |od| %>
  <%# raise f.object.metric_details.inspect %>
    <%#=   check_box_tag :metric_order_number %> <%#`	``= od.object.metric_detail.name%>
    <%#=   od.input :metric_detail_id, value: od.object.metric_detail.try(:name) %>
  <%# end %>

  <%= f.button :submit, class: 'btn btn-info' %>


<div class="container">
<ul id="sortable">
  <% MetricDetail.all.each_with_index  do |x, index| %>
    <li class="ui-state-default">
      <%= text_field_tag  "metric_dashboard_view[metric_detail_ids[]", x.name  %>
     </li>
  <% end %>
</ul>  
</div>
<% end %> 

<!-- 
<div class="container">
  <div class="row">
    <div class="col-sm" style="border: 1px solid red">
      1/3
    </div>
    <div class="col-sm">
      1/3
    </div>
    <div class="col-sm">
      1/3
    </div>
  </div>
</div> -->
 
	
    <script>
 
$(function () {
    $("#sortable").sortable({
        update: function (event, ui) {
            var order = $(this).sortable('serialize');
        }
    }).disableSelection();
    $('button').on('click', function () {
        var a = $("#sortable").sortable("serialize", {
            attribute: "id"
        });
        console.log(a);
        $.ajax({
            data: a,
            type: 'POST',
            url: 'saverank.php'
        });
    });
});


  </script>

    <style>
  #sortable { list-style-type: none; margin: 0; padding: 0; width: 1250; }
  #sortable li { margin: 3px 3px 3px 0; padding: 1px; float: left; width: 366px; height: 40px;  text-align: center; }
  </style>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in double" >
    <%= message %>
  </div>
<% end %>

<style type="text/css">
.double {border-style: double;}
</style>